In [32]:
import numpy as np
import pandas as pd

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import datetime as datetime
from datetime import datetime

!pip install geopandas   # If geopandas is not installed, this code should be activated.
import geopandas as gpd # For working with geospatial data
!pip install folium
import folium as fm     # folium has more dynamic maps - but requires internet connection
import matplotlib.pyplot as plt
from shapely.geometry import Point, Polygon

Requirement already satisfied: geopandas in /opt/anaconda3/lib/python3.9/site-packages (0.12.2)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.9/site-packages (from geopandas) (21.3)
Requirement already satisfied: pyproj>=2.6.1.post1 in /opt/anaconda3/lib/python3.9/site-packages (from geopandas) (3.4.1)
Requirement already satisfied: pandas>=1.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from geopandas) (1.4.4)
Requirement already satisfied: fiona>=1.8 in /opt/anaconda3/lib/python3.9/site-packages (from geopandas) (1.8.22)
Requirement already satisfied: shapely>=1.7 in /opt/anaconda3/lib/python3.9/site-packages (from geopandas) (2.0.0)
Requirement already satisfied: six>=1.7 in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (1.16.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (2022.9.24)
Requirement already satisfied: click-plugins>=1.0 in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: munch in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: attrs>=17 in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (22.1.0)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (65.5.0)
Requirement already satisfied: cligj>=0.5 in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (0.7.2)
Requirement already satisfied: click>=4.0 in /opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (8.0.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.0.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.0.0->geopandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.0.0->geopandas) (1.21.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/anaconda3/lib/python3.9/site-packages (from packaging->geopandas) (3.0.9)
Requirement already satisfied: folium in /opt/anaconda3/lib/python3.9/site-packages (0.14.0)
Requirement already satisfied: jinja2>=2.9 in /opt/anaconda3/lib/python3.9/site-packages (from folium) (2.11.3)
Requirement already satisfied: branca>=0.6.0 in /opt/anaconda3/lib/python3.9/site-packages (from folium) (0.6.0)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.9/site-packages (from folium) (2.28.1)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.9/site-packages (from folium) (1.21.5)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/anaconda3/lib/python3.9/site-packages (from jinja2>=2.9->folium) (2.0.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/anaconda3/lib/python3.9/site-packages (from requests->folium) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/anaconda3/lib/python3.9/site-packages (from requests->folium) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.9/site-packages (from requests->folium) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.9/site-packages (from requests->folium) (3.4)

In [33]:
data_2016 = pd.read_csv("/Users/akhil/Documents/Fire Vulnerability Project/Input Data/2016.csv")
data_2017 = pd.read_csv("/Users/akhil/Documents/Fire Vulnerability Project/Input Data/2017.csv")

data_2016

,MasterIncidentNumber,CalendarYear,Month,DayOfMonth,Call_Type,Problem,Battalion,Jurisdiction,ResponseArea,PriorityDescription,Response Status,Districts,Location 1
0,"16,000,015","2,016",Jan,1,Fire,TRASH - Trash Fire,B4,AFD,00-2004,3F,Code 3,5.0,"(30218836, 97806156)"
1,"16,000,017","2,016",Jan,1,Fire,TRASH - Trash Fire,B4,AFD,00-3606,3F,Code 1,2.0,"(30183275, 97786233)"
2,"16,000,038","2,016",Jan,1,Fire,BBQ - Unsafe Cooking,B2,AFD,00-3102,4F,Code 1,10.0,"(30363743, 97791275)"
3,"16,000,045","2,016",Jan,1,Fire,DUMP - Dumpster Fire,B3,AFD,00-1801,3F,Code 3,1.0,"(30318719, 97665985)"
4,"16,000,069","2,016",Jan,1,Fire,TRASH - Trash Fire,B5,AFD,00-2402,3F,Code 1,2.0,"(30195769, 97739084)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,"16,003,972","2,016",Jan,14,Fire,GRASS - Small Grass Fire,B3,AFD,00-4003,3F,Code 3,1.0,"(30379306, 9.765421E+7)"
686,"16,008,080","2,016",Jan,27,Fire,AUTO - Auto Fire,B5,AFD,00-3501,2F,Code 3,2.0,"(3.02153E+7, 97751378)"
687,"16,027,714","2,016",Mar,27,Fire,AUTO - Auto Fire,B3,AFD,00-2606,2F,Code 3,1.0,"(3.029124E+7, 97627952)"
688,"16,014,050","2,016",Feb,15,Fire,TRASH - Trash Fire,B5,AFD,00-0701,3F,Code 3,3.0,"(3.026215E+7, 97726965)"
689,"16,027,523","2,016",Mar,26,Fire,DUMP - Dumpster Fire,B5,AFD,00-2205,3F,Code 3,3.0,"(3.022632E+7, 97693756)"

In [34]:
data_2017

,MasterIncidentNumber,CalendarYear,Month,DayOfMonth,Call_Type,Problem,Battalion,Jurisdiction,ResponseArea,PriorityDescription,Response Status,Districts,Location 1
0,"17,093,562","2,017",Sep,22,Fire,ELEC - Electrical Fire,B1,AFD,00-0202,3F,Code 3,9.0,"(3.027827E+7, 97750572)"
1,"17,000,052","2,017",Jan,1,Fire,DUMP - Dumpster Fire,B3,AFD,00-1805,3F,Code 3,1.0,"(3.03285E+7, 97689363)"
2,"17,020,652","2,017",Feb,28,Fire,ELEC - Electrical Fire,B4,AFD,00-1102,3F,Left Blank,5.0,"(3.023976E+7, 97787699)"
3,"17,088,693","2,017",Sep,8,Fire,AUTO - Auto Fire,B3,AFD,00-1903,2F,Code 3,10.0,"(30337419, 9.775705E+7)"
4,"17,008,374","2,017",Jan,24,Fire,AUTO - Auto Fire,B2,AFD,00-3901,2F,Code 3,6.0,"(3.041475E+7, 97848298)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2786,"17,028,757","2,017",Mar,23,Fire,GRASS - Small Grass Fire,B3,AFD,00-2101,3F,Code 3,10.0,"(30358688, 97746673)"
2787,"17,062,308","2,017",Jun,26,Fire,ELEC - Electrical Fire,B3,AFD,00-0801,3F,Other,4.0,"(30372163, 97723397)"
2788,"17,072,490","2,017",Jul,25,Fire,ELEC - Electrical Fire,B3,AFD,00-2801,3F,Code 3,7.0,"(30402761, 97679086)"
2789,"17,028,592","2,017",Mar,23,Fire,GRASS - Small Grass Fire,B2,AFD,00-2503,3F,Code 3,10.0,"(30394168, 97748314)"
2790,"17,127,292","2,017",Dec,29,Fire,ELEC - Electrical Fire,B5,AFD,00-4204,3F,Code 3,2.0,"(30202269, 97670862)"

In [35]:
data_2016_2017 = data_2016 + data_2017

def string_parser(string):

    #Finds the comma separating the two values
    separator_location = string.rfind(",")
    
    #Separate individual values from the combined string
    lat_output = string[1:separator_location]
    long_output = string[separator_location+2:(len(string)-1)]

    #Prep for float conversion by adding decimal places
    #lat_output = lat_output[:2] + "." + lat_output[2:]
    #long_output = long_output[:2] + "." + long_output[2:]

    #Convert to float
    lat_output = float(lat_output)/(10**6)
    long_output = float(long_output)/(10**6)


    #Correct back to the western hemisphere
    long_output = long_output*-1
    
    return [lat_output,long_output]

In [36]:
data_2016['lat'] = data_2016.apply(lambda row : string_parser(row["Location 1"])[0], axis = 1)
data_2016['long'] = data_2016.apply(lambda row : string_parser(row["Location 1"])[1], axis = 1)
#data_2016["output_lat_long"] = string_parser(data_2016["Location 1"])
#data_2016["lat"] = string_parser(data_2016["Location 1"][0])[0]
#data_2016["long"] = string_parser(data_2016["Location 1"][1])[1]

data_2016

,MasterIncidentNumber,CalendarYear,Month,DayOfMonth,Call_Type,Problem,Battalion,Jurisdiction,ResponseArea,PriorityDescription,Response Status,Districts,Location 1,lat,long
0,"16,000,015","2,016",Jan,1,Fire,TRASH - Trash Fire,B4,AFD,00-2004,3F,Code 3,5.0,"(30218836, 97806156)",30.218836,-97.806156
1,"16,000,017","2,016",Jan,1,Fire,TRASH - Trash Fire,B4,AFD,00-3606,3F,Code 1,2.0,"(30183275, 97786233)",30.183275,-97.786233
2,"16,000,038","2,016",Jan,1,Fire,BBQ - Unsafe Cooking,B2,AFD,00-3102,4F,Code 1,10.0,"(30363743, 97791275)",30.363743,-97.791275
3,"16,000,045","2,016",Jan,1,Fire,DUMP - Dumpster Fire,B3,AFD,00-1801,3F,Code 3,1.0,"(30318719, 97665985)",30.318719,-97.665985
4,"16,000,069","2,016",Jan,1,Fire,TRASH - Trash Fire,B5,AFD,00-2402,3F,Code 1,2.0,"(30195769, 97739084)",30.195769,-97.739084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,"16,003,972","2,016",Jan,14,Fire,GRASS - Small Grass Fire,B3,AFD,00-4003,3F,Code 3,1.0,"(30379306, 9.765421E+7)",30.379306,-97.654210
686,"16,008,080","2,016",Jan,27,Fire,AUTO - Auto Fire,B5,AFD,00-3501,2F,Code 3,2.0,"(3.02153E+7, 97751378)",30.215300,-97.751378
687,"16,027,714","2,016",Mar,27,Fire,AUTO - Auto Fire,B3,AFD,00-2606,2F,Code 3,1.0,"(3.029124E+7, 97627952)",30.291240,-97.627952
688,"16,014,050","2,016",Feb,15,Fire,TRASH - Trash Fire,B5,AFD,00-0701,3F,Code 3,3.0,"(3.026215E+7, 97726965)",30.262150,-97.726965
689,"16,027,523","2,016",Mar,26,Fire,DUMP - Dumpster Fire,B5,AFD,00-2205,3F,Code 3,3.0,"(3.022632E+7, 97693756)",30.226320,-97.693756

2017 has worse data quality and thus requires a different approach

In [37]:
print(data_2017["Location 1"])

0       (3.027827E+7, 97750572)
1        (3.03285E+7, 97689363)
2       (3.023976E+7, 97787699)
3       (30337419, 9.775705E+7)
4       (3.041475E+7, 97848298)
                 ...
2786       (30358688, 97746673)
2787       (30372163, 97723397)
2788       (30402761, 97679086)
2789       (30394168, 97748314)
2790       (30202269, 97670862)
Name: Location 1, Length: 2791, dtype: object

In [38]:
def string_2017_parser(string):

    #Finds the comma separating the two values
    separator_location = string.rfind(",")
    
    #Separate individual values from the combined string
    lat_output = string[1:separator_location]
    long_output = string[separator_location+2:(len(string)-1)]

    lat_output = float(lat_output)/(10**6)
    long_output = float(long_output)/(10**6)


    #Correct back to the western hemisphere
    long_output = long_output*-1
    
    return [lat_output,long_output]

In [39]:
#data_2017["lat"] = string_2017_parser(data_2017["Location 1"][0])[0]
#data_2017["long"] = string_2017_parser(data_2017["Location 1"][1])[1]

data_2017['lat'] = data_2017.apply(lambda row : string_2017_parser(row["Location 1"])[0], axis = 1)
data_2017['long'] = data_2017.apply(lambda row : string_2017_parser(row["Location 1"])[1], axis = 1)

data_2017

all_data = pd.concat([data_2016,data_2017])

In [40]:
data_2017

,MasterIncidentNumber,CalendarYear,Month,DayOfMonth,Call_Type,Problem,Battalion,Jurisdiction,ResponseArea,PriorityDescription,Response Status,Districts,Location 1,lat,long
0,"17,093,562","2,017",Sep,22,Fire,ELEC - Electrical Fire,B1,AFD,00-0202,3F,Code 3,9.0,"(3.027827E+7, 97750572)",30.278270,-97.750572
1,"17,000,052","2,017",Jan,1,Fire,DUMP - Dumpster Fire,B3,AFD,00-1805,3F,Code 3,1.0,"(3.03285E+7, 97689363)",30.328500,-97.689363
2,"17,020,652","2,017",Feb,28,Fire,ELEC - Electrical Fire,B4,AFD,00-1102,3F,Left Blank,5.0,"(3.023976E+7, 97787699)",30.239760,-97.787699
3,"17,088,693","2,017",Sep,8,Fire,AUTO - Auto Fire,B3,AFD,00-1903,2F,Code 3,10.0,"(30337419, 9.775705E+7)",30.337419,-97.757050
4,"17,008,374","2,017",Jan,24,Fire,AUTO - Auto Fire,B2,AFD,00-3901,2F,Code 3,6.0,"(3.041475E+7, 97848298)",30.414750,-97.848298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2786,"17,028,757","2,017",Mar,23,Fire,GRASS - Small Grass Fire,B3,AFD,00-2101,3F,Code 3,10.0,"(30358688, 97746673)",30.358688,-97.746673
2787,"17,062,308","2,017",Jun,26,Fire,ELEC - Electrical Fire,B3,AFD,00-0801,3F,Other,4.0,"(30372163, 97723397)",30.372163,-97.723397
2788,"17,072,490","2,017",Jul,25,Fire,ELEC - Electrical Fire,B3,AFD,00-2801,3F,Code 3,7.0,"(30402761, 97679086)",30.402761,-97.679086
2789,"17,028,592","2,017",Mar,23,Fire,GRASS - Small Grass Fire,B2,AFD,00-2503,3F,Code 3,10.0,"(30394168, 97748314)",30.394168,-97.748314
2790,"17,127,292","2,017",Dec,29,Fire,ELEC - Electrical Fire,B5,AFD,00-4204,3F,Code 3,2.0,"(30202269, 97670862)",30.202269,-97.670862

In [41]:
all_data

,MasterIncidentNumber,CalendarYear,Month,DayOfMonth,Call_Type,Problem,Battalion,Jurisdiction,ResponseArea,PriorityDescription,Response Status,Districts,Location 1,lat,long
0,"16,000,015","2,016",Jan,1,Fire,TRASH - Trash Fire,B4,AFD,00-2004,3F,Code 3,5.0,"(30218836, 97806156)",30.218836,-97.806156
1,"16,000,017","2,016",Jan,1,Fire,TRASH - Trash Fire,B4,AFD,00-3606,3F,Code 1,2.0,"(30183275, 97786233)",30.183275,-97.786233
2,"16,000,038","2,016",Jan,1,Fire,BBQ - Unsafe Cooking,B2,AFD,00-3102,4F,Code 1,10.0,"(30363743, 97791275)",30.363743,-97.791275
3,"16,000,045","2,016",Jan,1,Fire,DUMP - Dumpster Fire,B3,AFD,00-1801,3F,Code 3,1.0,"(30318719, 97665985)",30.318719,-97.665985
4,"16,000,069","2,016",Jan,1,Fire,TRASH - Trash Fire,B5,AFD,00-2402,3F,Code 1,2.0,"(30195769, 97739084)",30.195769,-97.739084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2786,"17,028,757","2,017",Mar,23,Fire,GRASS - Small Grass Fire,B3,AFD,00-2101,3F,Code 3,10.0,"(30358688, 97746673)",30.358688,-97.746673
2787,"17,062,308","2,017",Jun,26,Fire,ELEC - Electrical Fire,B3,AFD,00-0801,3F,Other,4.0,"(30372163, 97723397)",30.372163,-97.723397
2788,"17,072,490","2,017",Jul,25,Fire,ELEC - Electrical Fire,B3,AFD,00-2801,3F,Code 3,7.0,"(30402761, 97679086)",30.402761,-97.679086
2789,"17,028,592","2,017",Mar,23,Fire,GRASS - Small Grass Fire,B2,AFD,00-2503,3F,Code 3,10.0,"(30394168, 97748314)",30.394168,-97.748314
2790,"17,127,292","2,017",Dec,29,Fire,ELEC - Electrical Fire,B5,AFD,00-4204,3F,Code 3,2.0,"(30202269, 97670862)",30.202269,-97.670862

In [42]:
gdf_2016_2017 = gpd.GeoDataFrame(
    all_data, geometry=gpd.points_from_xy(all_data.long, all_data.lat), crs="EPSG:4326")

Import the 2018-2021 Data

In [43]:
gdf_2018_2021 = gpd.read_file("/Users/akhil/Documents/Fire Vulnerability Project/Input Data/AFD Fire Incidents 2018-2021/geo_export_11a4046f-83de-4712-b666-24e7911446ab.shp", crs="EPSG:4326")

In [44]:
gdf_2018_2021["calendarye"] = pd.to_numeric(gdf_2018_2021["calendarye"])

In [45]:
gdf_2018_2020 = gdf_2018_2021.loc[gdf_2018_2021["calendarye"] < 2021]

In [46]:
gdf_2018_2020

,incidentnu,calendarye,month,date_incda,time_incda,call_type,problem,responsear,jurisdicti,priorityde,council_di,geometry
0,20139377,2020,Dec,2020-12-29,00:00:00.000,Fire,AUTO - Auto Fire,00-0701,AFD,2F,3,POINT (-97.72651 30.25049)
1,18050381,2018,May,2018-05-20,00:00:00.000,Fire,TRASH - Trash Fire,00-0501,AFD,3F,3,POINT (-97.68956 30.26480)
2,20046163,2020,May,2020-05-01,00:00:00.000,Fire,AUTO - Auto Fire,00-3111,AFD,2F,10,POINT (-97.83031 30.32466)
3,18011035,2018,Jan,2018-01-29,00:00:00.000,Fire,GRASS - Small Grass Fire,00-4004,AFD,3F,7,POINT (-97.67304 30.39916)
5,18078725,2018,Aug,2018-08-01,00:00:00.000,Fire,BBQ - Unsafe Cooking,00-2101,AFD,4F,10,POINT (-97.74799 30.36069)
...,...,...,...,...,...,...,...,...,...,...,...,...
19540,18046570,2018,May,2018-05-11,00:00:00.000,Fire,AUTO - Auto Fire,00-1603,AFD,2F,4,POINT (-97.70707 30.32507)
19541,19000553,2019,Jan,2019-01-02,00:00:00.000,Fire,ELEC - Electrical Fire,00-2901,AFD,3F,8,POINT (-97.84954 30.19812)
19543,20025519,2020,Mar,2020-03-04,00:00:00.000,Fire,AUTO - Auto Fire,00-4901,AFD,2F,5,POINT (-97.81206 30.10195)
19550,20046507,2020,May,2020-05-02,00:00:00.000,Fire,GRASS - Small Grass Fire,00-0601,AFD,3F,9,POINT (-97.73705 30.24897)
19551,18107045,2018,Oct,2018-10-16,00:00:00.000,Fire,BOX -Structure Fire,00-1504,AFD,1F,1,POINT (-97.70264 30.27809)

In [47]:
gdf_2016_2017.drop(columns=["Battalion","Response Status"],inplace=True)

In [48]:
gdf_2016_2017.rename(columns={'MasterIncidentNumber': 'incidentnu','CalendarYear': 'calendarye','Month':'month','Call_Type':'call_type','Problem':'problem','Jurisdiction':'jurisdicti','PriorityDescription':'priorityde'}, inplace=True)

In [49]:
gdf_2016_2017.rename(columns={'Districts':'council_di','ResponseArea':'responsear'}, inplace=True)

In [50]:
gdf_2016_2017["incidentnu"] = gdf_2016_2017["incidentnu"].str.replace(',', '').astype(int)
gdf_2016_2017["calendarye"] = gdf_2016_2017["calendarye"].str.replace(',', '').astype(int)

In [51]:
gdf_2016_2017["rough_date"] = gdf_2016_2017["calendarye"].apply(str) + " " + gdf_2016_2017["month"] + " " + gdf_2016_2017["DayOfMonth"].apply(str)

In [52]:
gdf_2016_2017["date_incda"] = pd.to_datetime(gdf_2016_2017["rough_date"], errors="raise", format="%Y %b %d")

In [53]:
gdf_2018_2020["date_incda"] = pd.to_datetime(gdf_2018_2020["date_incda"])

/opt/anaconda3/lib/python3.9/site-packages/geopandas/geodataframe.py:1443: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [54]:
gdf_2016_2017.drop(columns=["DayOfMonth","lat","long","Location 1","rough_date"],inplace=True)

In [55]:
gdf_2016_2017

,incidentnu,calendarye,month,call_type,problem,jurisdicti,responsear,priorityde,council_di,geometry,date_incda
0,16000015,2016,Jan,Fire,TRASH - Trash Fire,AFD,00-2004,3F,5.0,POINT (-97.80616 30.21884),2016-01-01
1,16000017,2016,Jan,Fire,TRASH - Trash Fire,AFD,00-3606,3F,2.0,POINT (-97.78623 30.18327),2016-01-01
2,16000038,2016,Jan,Fire,BBQ - Unsafe Cooking,AFD,00-3102,4F,10.0,POINT (-97.79127 30.36374),2016-01-01
3,16000045,2016,Jan,Fire,DUMP - Dumpster Fire,AFD,00-1801,3F,1.0,POINT (-97.66599 30.31872),2016-01-01
4,16000069,2016,Jan,Fire,TRASH - Trash Fire,AFD,00-2402,3F,2.0,POINT (-97.73908 30.19577),2016-01-01
...,...,...,...,...,...,...,...,...,...,...,...
2786,17028757,2017,Mar,Fire,GRASS - Small Grass Fire,AFD,00-2101,3F,10.0,POINT (-97.74667 30.35869),2017-03-23
2787,17062308,2017,Jun,Fire,ELEC - Electrical Fire,AFD,00-0801,3F,4.0,POINT (-97.72340 30.37216),2017-06-26
2788,17072490,2017,Jul,Fire,ELEC - Electrical Fire,AFD,00-2801,3F,7.0,POINT (-97.67909 30.40276),2017-07-25
2789,17028592,2017,Mar,Fire,GRASS - Small Grass Fire,AFD,00-2503,3F,10.0,POINT (-97.74831 30.39417),2017-03-23
2790,17127292,2017,Dec,Fire,ELEC - Electrical Fire,AFD,00-4204,3F,2.0,POINT (-97.67086 30.20227),2017-12-29

In [56]:
gdf_2018_2020.drop(columns=["time_incda"],inplace=True)

/var/folders/z3/kchg1fx10r126g5rwh_ntl5w0000gp/T/ipykernel_4783/4010629409.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf_2018_2020.drop(columns=["time_incda"],inplace=True)

In [57]:
gdf_2016_2017 = gdf_2016_2017.to_crs("EPSG:4326")
gdf_2018_2020 = gdf_2018_2020.to_crs("EPSG:4326")
gdf_2016_2020 = pd.concat([gdf_2016_2017,gdf_2018_2020])

In [58]:
gdf_2016_2020.drop(columns=["date_incda"],inplace=True)

In [59]:
gdf_2016_2020

,incidentnu,calendarye,month,call_type,problem,jurisdicti,responsear,priorityde,council_di,geometry
0,16000015,2016,Jan,Fire,TRASH - Trash Fire,AFD,00-2004,3F,5.0,POINT (-97.80616 30.21884)
1,16000017,2016,Jan,Fire,TRASH - Trash Fire,AFD,00-3606,3F,2.0,POINT (-97.78623 30.18327)
2,16000038,2016,Jan,Fire,BBQ - Unsafe Cooking,AFD,00-3102,4F,10.0,POINT (-97.79127 30.36374)
3,16000045,2016,Jan,Fire,DUMP - Dumpster Fire,AFD,00-1801,3F,1.0,POINT (-97.66599 30.31872)
4,16000069,2016,Jan,Fire,TRASH - Trash Fire,AFD,00-2402,3F,2.0,POINT (-97.73908 30.19577)
...,...,...,...,...,...,...,...,...,...,...
19540,18046570,2018,May,Fire,AUTO - Auto Fire,AFD,00-1603,2F,4,POINT (-97.70707 30.32507)
19541,19000553,2019,Jan,Fire,ELEC - Electrical Fire,AFD,00-2901,3F,8,POINT (-97.84954 30.19812)
19543,20025519,2020,Mar,Fire,AUTO - Auto Fire,AFD,00-4901,2F,5,POINT (-97.81206 30.10195)
19550,20046507,2020,May,Fire,GRASS - Small Grass Fire,AFD,00-0601,3F,9,POINT (-97.73705 30.24897)
19551,18107045,2018,Oct,Fire,BOX -Structure Fire,AFD,00-1504,1F,1,POINT (-97.70264 30.27809)

In [60]:
#gdf_2016_2020.to_file("fire_incidents_v2.shp")